name: Build Initrd Only

on:
  workflow_dispatch:
    inputs:
      artifact_id:
        description: "Artifact ID from source workflow"
        required: true
        default: "16826209790"  # 替换成你的实际Artifact ID

permissions:
  contents: read
  actions: read

jobs:
  build_initrd:
    runs-on: ubuntu-22.04
    steps:
      # 第一步：通过API下载Artifact
      - name: Download artifact via API
        run: |
          mkdir -p kernel_temp
          curl -sL \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ inputs.artifact_id }}/zip" \
            -o kernel_temp/artifact.zip
          
          unzip kernel_temp/artifact.zip -d kernel_temp/
          rm kernel_temp/artifact.zip

      # 第二步：验证文件结构
      - name: Verify downloaded files
        run: |
          echo "文件列表："
          find kernel_temp -type f
          [ -f "kernel_temp/armbian_boot_files/vmlinuz-6.16.0" ] || { echo "未找到内核文件"; exit 1; }

      # 第三步：设置环境变量（保持与你原始配置一致）
      - name: Set environment paths
        run: |
          echo "src_path=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "armbian_file_path=$GITHUB_WORKSPACE/armbian_boot_files" >> $GITHUB_ENV
          echo "kernel_main_version=6.16.0" >> $GITHUB_ENV

      # 第四步：移动文件到目标位置
      - name: Organize files
        run: |
          mkdir -p ${{ env.armbian_file_path }}
          cp -r kernel_temp/armbian_boot_files/* ${{ env.armbian_file_path }}/
          ls -lh ${{ env.armbian_file_path }}

          


      - name: Generate initrd.img
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap qemu-user-static
          sudo apt-get install -y initramfs-tools  u-boot-tools
          mkdir -p ${{ env.src_path }}/chroot_dir
          mkdir -p ${{ env.src_path }}/lib/modules
          mkdir -p ${{ env.src_path }}/chroot_dir/usr/bin/
          mv ${{ env.armbian_file_path }}/${{ env.kernel_main_version }}  ${{ env.src_path }}/lib/modules
          sudo cp /usr/bin/qemu-aarch64-static ${{ env.src_path }}/chroot_dir/usr/bin/
          sudo cp /etc/resolv.conf ${{ env.src_path }}/chroot_dir/etc/
          sudo chroot ${{ env.src_path }}/chroot_dir bash -c "echo 'deb http://ports.ubuntu.com/ jammy main' > /etc/apt/sources.list"
          
          sudo debootstrap --arch=arm64 --variant=minbase jammy ${{ env.src_path }}/chroot_dir http://ports.ubuntu.com/
          
          sudo mount -t proc proc ${{ env.src_path }}/chroot_dir/proc
          sudo mount -t sysfs sys ${{ env.src_path }}/chroot_dir/sys
          sudo mount -o bind /dev ${{ env.src_path }}/chroot_dir/dev
          sudo mount -o bind ${{ env.src_path }}/lib/modules ${{ env.src_path }}/chroot_dir/lib/modules
          sudo chroot ${{ env.src_path }}/chroot_dir /bin/bash <<EOF
          apt-get update
          apt-get install -y apt-utils dialog locales  locale-gen en_US.UTF-8
          apt-get install -y initramfs-tools u-boot-tools
          
          mkdir -p /boot
          mkinitramfs -c xz -o /boot/initrd.img-${{ env.kernel_main_version }}  ${{ env.kernel_main_version }}
          mkimage -A arm64 -O linux -T ramdisk -C none -a 0 -e 0 -n uInitrd -d /boot/initrd.img-${{ env.kernel_main_version }} /boot/uInitrd-${{ env.kernel_main_version }}
          EOF
          
      - name: Clean up
        run: |
          sudo umount ${{ env.src_path }}/chroot_dir/dev
          sudo umount ${{ env.src_path }}/chroot_dir/proc
          sudo umount ${{ env.src_path }}/chroot_dir/sys
          ls -lh ${{ env.src_path }}/chroot_dir/boot/
          

