name: test_initrd

on:
  workflow_dispatch:
    inputs:
      first_workflow_run_id:
        description: "第一个 workflow 的 Run ID（例如：16829068004）"
        default: "16829068004"
        required: true
      kernel_version:
        description: "内核版本（例如：6.16.0）"
        default: "6.16.0"
        required: true

jobs:
  build_initrd:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set kernel version
        run: |
          echo "kernel_main_version=${{ github.event.inputs.kernel_version }}" >> $GITHUB_ENV
          echo "使用指定的内核版本: ${{ github.event.inputs.kernel_version }}"

      - name: Download artifact from first workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 通过 GitHub API 获取 Artifact 下载地址
          ARTIFACT_URL=$(curl -s \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.inputs.first_workflow_run_id }}/artifacts" \
            | jq -r '.artifacts[] | select(.name == "kernel-build") | .archive_download_url')

          if [ -z "$ARTIFACT_URL" ]; then
            echo "错误：找不到 kernel-build Artifact"
            exit 1
          fi

          # 下载并解压 Artifact
          curl -L -o kernel-build.zip \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            "$ARTIFACT_URL"
          unzip kernel-build.zip -d kernel_artifacts
          ls -lh kernel_artifacts/

      - name: Verify kernel modules
        run: |
          if [ ! -d "kernel_artifacts/${{ env.kernel_main_version }}" ]; then
            echo "错误：内核模块目录不存在: kernel_artifacts/${{ env.kernel_main_version }}"
            exit 1
          fi

      - name: Prepare directories
        run: |
          sudo mkdir -p /mnt/chroot/lib/modules
          sudo cp -a kernel_artifacts/${{ env.kernel_main_version }} /mnt/chroot/lib/modules/

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap qemu-user-static initramfs-tools u-boot-tools

      - name: Setup base system
        run: |
          sudo debootstrap --arch=arm64 --variant=minbase jammy /mnt/chroot http://ports.ubuntu.com/
          
          # 准备 chroot 环境
          sudo cp /usr/bin/qemu-aarch64-static /mnt/chroot/usr/bin/
          sudo cp /etc/resolv.conf /mnt/chroot/etc/
          
          # 挂载必要的文件系统
          sudo mount -t proc proc /mnt/chroot/proc
          sudo mount -t sysfs sys /mnt/chroot/sys
          sudo mount -o bind /dev /mnt/chroot/dev

      - name: Pre-configure chroot environment
        run: |
          sudo chroot /mnt/chroot /bin/bash <<'PREEOF'
          # 配置完整的软件源
          echo "deb http://ports.ubuntu.com/ubuntu-ports jammy main universe multiverse" > /etc/apt/sources.list
          echo "deb http://ports.ubuntu.com/ubuntu-ports jammy-updates main universe multiverse" >> /etc/apt/sources.list
          echo "deb http://ports.ubuntu.com/ubuntu-ports jammy-security main universe multiverse" >> /etc/apt/sources.list
          
          # 更新软件包列表
          apt-get update -y
          PREEOF

      - name: Build initrd in chroot
        run: |
          sudo chroot /mnt/chroot /bin/bash <<'EOF'
          # 安装必要软件包（使用完整包名和明确的安装选项）
          apt-get install -y --no-install-recommends \
            locales \
            dialog \
            apt-utils \
            initramfs-tools \
            u-boot-tools \
            busybox-static \
            kmod \
            linux-base

          # 配置 locale
          echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
          /usr/sbin/locale-gen en_US.UTF-8
          
          # 创建 boot 目录
          mkdir -p /boot
          cd /boot
          # 生成 initrd
          echo "正在生成 initrd.img-${{ env.kernel_main_version }}"
          [[ -f "/etc/initramfs-tools/update-initramfs.conf" ]] && sed -i "s|^update_initramfs=.*|update_initramfs=no|g" /etc/initramfs-tools/update-initramfs.conf
          update-initramfs -c -k  ${{ env.kernel_main_version }}
          
          # 生成 uInitrd
          echo "正在生成 uInitrd-${{ env.kernel_main_version }}"
          if ! /usr/bin/mkimage -A arm64 -O linux -T ramdisk -C gzip -a 0 -e 0 -n uInitrd \
            -d /boot/initrd.img-${{ env.kernel_main_version }} /boot/uInitrd-${{ env.kernel_main_version }}; then
            echo "mkimage 执行失败，尝试重新安装 u-boot-tools..."
            apt-get install -y --reinstall u-boot-tools
            /usr/bin/mkimage -A arm64 -O linux -T ramdisk -C gzip -a 0 -e 0 -n uInitrd \
              -d /boot/initrd.img-${{ env.kernel_main_version }} /boot/uInitrd-${{ env.kernel_main_version }}
          fi
          
          # 验证生成的文件
          ls -lh /boot/initrd.img-${{ env.kernel_main_version }} /boot/uInitrd-${{ env.kernel_main_version }}
          EOF

      - name: Collect results
        run: |
          sudo mkdir -p initrd_results
          sudo cp /mnt/chroot/boot/initrd.img-${{ env.kernel_main_version }} initrd_results/
          sudo cp /mnt/chroot/boot/uInitrd-${{ env.kernel_main_version }} initrd_results/
          ls -lh initrd_results/

      - name: Clean up
        run: |
          sudo umount /mnt/chroot/dev
          sudo umount /mnt/chroot/proc
          sudo umount /mnt/chroot/sys
          sudo rm -rf /mnt/chroot

      - name: Upload initrd artifacts
        uses: actions/upload-artifact@v4
        with:
          name: initrd-build-${{ env.kernel_main_version }}
          path: initrd_results/
          retention-days: 3
